controller:
  watchIngressWithoutClass: true
  hostNetwork: true
  hostPort:
    enabled: true
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
  ingressClass: nginx
  kind: DaemonSet
  admissionWebhooks:
    patch:
      enabled: true
  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443
      tcp:
        8080: 32808
defaultBackend:
  enabled: true
